import React from 'react';
import api from '../api/axios';

function Checkout({ cart, onClear, onSaleSuccess }) {
  // Calculate total price for the transaction
  const total = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);

  const handleCheckout = async (method) => {
    if (cart.length === 0) return alert("Cart is empty!");

    const saleData = {
      items: cart,
      totalAmount: total,
      paymentMethod: method // 'Cash' or 'M-Pesa'
    };

    try {
      // 1. Send the sale to the Backend (Brain)
      const response = await api.post('/sales', saleData);

      // 2. PASS DATA TO APP.JS (This triggers the Receipt Modal)
      // We combine the saleData with the ID generated by MySQL
      onSaleSuccess({ 
        ...saleData, 
        id: response.data.newSale.id 
      });

      // 3. Reset the cart for the next customer
      onClear();

    } catch (err) {
      console.error("Checkout error:", err);
      alert("❌ Sale failed! Check if your backend server is running.");
    }
  };

  return (
    <div style={styles.sidebar}>
      <h2 style={styles.title}>Current Order</h2>
      <hr />

      <div style={styles.itemList}>
        {cart.length === 0 ? (
          <p style={styles.empty}>No drinks added yet...</p>
        ) : (
          cart.map((item) => (
            <div key={item.id} style={styles.itemRow}>
              <span>{item.name} x {item.quantity}</span>
              <span>KES {(item.price * item.quantity).toLocaleString()}</span>
            </div>
          ))
        )}
      </div>

      <div style={styles.footer}>
        <div style={styles.totalRow}>
          <span>Total:</span>
          <span style={styles.totalPrice}>KES {total.toLocaleString()}</span>
        </div>

        <div style={styles.buttonGroup}>
          <button 
            onClick={() => handleCheckout('Cash')} 
            style={{ ...styles.btn, backgroundColor: '#28a745' }}
          >
            Cash
          </button>
          <button 
            onClick={() => handleCheckout('M-Pesa')} 
            style={{ ...styles.btn, backgroundColor: '#007bff' }}
          >
            M-Pesa
          </button>
        </div>
        
        <button onClick={onClear} style={styles.clearBtn}>Clear Order</button>
      </div>
    </div>
  );
}

const styles = {
  sidebar: { padding: '20px', display: 'flex', flexDirection: 'column', height: '100%' },
  title: { margin: '0 0 10px 0', fontSize: '1.5rem' },
  itemList: { flex: 1, overflowY: 'auto', margin: '20px 0' },
  itemRow: { display: 'flex', justifyContent: 'space-between', marginBottom: '10px', fontSize: '0.9rem' },
  empty: { color: '#888', fontStyle: 'italic' },
  footer: { borderTop: '2px solid #eee', paddingTop: '20px' },
  totalRow: { display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '1.2rem', marginBottom: '20px' },
  totalPrice: { color: '#2c3e50' },
  buttonGroup: { display: 'flex', gap: '10px' },
  btn: { flex: 1, color: 'white', border: 'none', padding: '12px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold' },
  clearBtn: { width: '100%', marginTop: '10px', background: 'none', border: 'none', color: '#d9534f', cursor: 'pointer', textDecoration: 'underline' }
};

export default Checkout;